### Variables
@baseUrl = http://localhost:3000
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjkzNzg5MzQsImV4cCI6MTc2OTM3OTgzNH0.8Iq4vi-NCqOnk0FXs9zN7IlY2WA6z13Zj2YFol7Bhxc
@userToken = #Copier le token après la requête de login user

### Login Admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin123"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "password123"
}

### GET tous les todos, sans pagination (USER ou ADMIN)
GET {{baseUrl}}/api/todos
Authorization: Bearer {{adminToken}}

### GET tous les todos - Page 1
GET {{baseUrl}}/api/todos?page=1&limit=5
Authorization: Bearer {{adminToken}}

### GET tous les todos - Page 2
GET {{baseUrl}}/api/todos?page=2&limit=5
Authorization: Bearer {{adminToken}}

### GET un todo par ID (USER ou ADMIN)
GET {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}

### POST créer un todo (ADMIN seulement)
POST {{baseUrl}}/api/todos
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Ma première tâche",
  "description": "Description de test",
  "priority": "HIGH",
  "status": "TODO",
  "dueDate": "2026-02-01T10:00:00Z"
}

### POST créer un todo avec USER (devrait échouer)
POST {{baseUrl}}/api/todos
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "title": "Tâche interdite",
  "priority": "LOW"
}

### PATCH mettre à jour un todo (ADMIN seulement)
PATCH {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Tâche mise à jour",
  "priority": "HIGH"
}

### DELETE un todo (ADMIN seulement)
DELETE {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}