### Variables
@baseUrl = http://localhost:3000
@adminToken = #Copier le token après la requête de login admin
@userToken = #Copier le token après la requête de login user

### Login Admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin123"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "password123"
}

### GET tous les todos, sans pagination (USER ou ADMIN)
GET {{baseUrl}}/api/todos
Authorization: Bearer {{adminToken}}

### GET tous les todos - Page 1
GET {{baseUrl}}/api/todos?page=1&limit=5
Authorization: Bearer {{adminToken}}

### GET tous les todos - Page 2
GET {{baseUrl}}/api/todos?page=2&limit=5
Authorization: Bearer {{adminToken}}

### POST pour test suivant
POST {{baseUrl}}/api/todos
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Projet urgent à finir",
  "priority": "HIGH",
  "categoryId": 2
}

### Chercher "urgent" (devrait trouver le todo ci-dessus)
GET {{baseUrl}}/api/todos?search=urgent
Authorization: Bearer {{adminToken}}

### Filtrer par categoryId
GET {{baseUrl}}/api/todos?categoryId=2
Authorization: Bearer {{adminToken}}

### Combiner filtres
GET {{baseUrl}}/api/todos?status=TODO&priority=HIGH&page=1&limit=5
Authorization: Bearer {{adminToken}}

### GET un todo par ID (USER ou ADMIN)
GET {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}

### POST créer un todo (ADMIN seulement)
POST {{baseUrl}}/api/todos
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Ma première tâche",
  "description": "Description de test",
  "priority": "HIGH",
  "status": "TODO",
  "dueDate": "2026-02-01T10:00:00Z"
}

### POST créer un todo avec USER (devrait échouer)
POST {{baseUrl}}/api/todos
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "title": "Tâche interdite",
  "priority": "LOW"
}

### PATCH mettre à jour un todo (ADMIN seulement)
PATCH {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Tâche mise à jour",
  "priority": "HIGH"
}

### DELETE un todo (ADMIN seulement)
DELETE {{baseUrl}}/api/todos/1
Authorization: Bearer {{adminToken}}